class AppData {
  static final List<Map<String, dynamic>> lessons = [
    {
      "title": "Lektion 1",
      "name": "Hallo! Ich bin Nicole",
      "topic": "سلام، معرفی، کشور و زبان",
      "grammar": "ich / du / Sie + sein, heißen, kommen, wohnen, sprechen, lernen",
      "words": [
        {"word": "der Name", "translation": "اسم"},
        {"word": "der Vorname", "translation": "نام"},
        {"word": "der Nachname", "translation": "نام خانوادگی"},
        {"word": "die Adresse", "translation": "آدرس"},
        {"word": "die Telefonnummer", "translation": "شماره تلفن"},
        {"word": "die E-Mail", "translation": "ایمیل"},
        {"word": "das Land", "translation": "کشور"},
        {"word": "die Sprache", "translation": "زبان"},
        {"word": "Deutschland", "translation": "آلمان"},
        {"word": "Iran", "translation": "ایران"},
        {"word": "Österreich", "translation": "اتریش"},
        {"word": "die Schweiz", "translation": "سوئیس"},
        {"word": "Frankreich", "translation": "فرانسه"},
        {"word": "Italien", "translation": "ایتالیا"},
        {"word": "Spanien", "translation": "اسپانیا"},
        {"word": "England", "translation": "انگلستان"},
        {"word": "die Türkei", "translation": "ترکیه"},
        {"word": "die USA", "translation": "ایالات متحده آمریکا"},
        {"word": "Deutsch", "translation": "آلمانی (زبان)"},
        {"word": "Persisch", "translation": "فارسی"},
        {"word": "Englisch", "translation": "انگلیسی"},
        {"word": "Französisch", "translation": "فرانسوی"},
        {"word": "Spanisch", "translation": "اسپانیایی"},
        {"word": "heißen", "translation": "نام داشتن"},
        {"word": "kommen", "translation": "آمدن / اهل جایی بودن"},
        {"word": "wohnen", "translation": "زندگی کردن"},
        {"word": "sprechen", "translation": "صحبت کردن"},
        {"word": "lernen", "translation": "یاد گرفتن"},
        {"word": "sein", "translation": "بودن"},
        {"word": "wer", "translation": "چه کسی"},
        {"word": "wie", "translation": "چطور / چگونه"},
        {"word": "wo", "translation": "کجا"},
        {"word": "woher", "translation": "از کجا"}
      ],
      "sentences": [
        {"de": "Guten Tag!", "fa": "روز بخیر!"},
        {"de": "Hallo, ich bin Nicole.", "fa": "سلام، من نیکول هستم."},
        {"de": "Wie heißt du?", "fa": "اسمت چیست؟"},
        {"de": "Ich heiße Ali.", "fa": "اسم من علی است."},
        {"de": "Wie heißen Sie?", "fa": "اسم شما چیست؟"},
        {"de": "Woher kommst du?", "fa": "اهل کجا هستی؟"},
        {"de": "Ich komme aus dem Iran.", "fa": "من اهل ایران هستم."},
        {"de": "Er kommt aus Deutschland.", "fa": "او اهل آلمان است."},
        {"de": "Wo wohnst du?", "fa": "کجا زندگی می‌کنی؟"},
        {"de": "Ich wohne in Khorramshahr.", "fa": "من در خرمشهر زندگی می‌کنم."},
        {"de": "Welche Sprache sprichst du?", "fa": "چه زبانی صحبت می‌کنی؟"},
        {"de": "Ich spreche Persisch und Englisch.", "fa": "من فارسی و انگلیسی صحبت می‌کنم."},
        {"de": "Ich lerne Deutsch.", "fa": "من آلمانی یاد می‌گیرم."},
        {"de": "Wie geht es dir?", "fa": "چطوری؟ / حالت چطوره؟"},
        {"de": "Danke, mir geht es gut.", "fa": "ممنون، حالم خوب است."}
      ]
    },
    {
      "title": "Lektion 2",
      "name": "Ich bin Journalistin",
      "topic": "اطلاعات شخصی، سن، شغل و کار",
      "grammar": "صرف فعل در زمان حال + sein / haben + اطلاعات شخصی",
      "words": [
        {"word": "der Beruf", "translation": "شغل"},
        {"word": "die Arbeit", "translation": "کار"},
        {"word": "die Firma", "translation": "شرکت"},
        {"word": "der Arzt", "translation": "پزشک مرد"},
        {"word": "die Ärztin", "translation": "پزشک زن"},
        {"word": "der Lehrer", "translation": "معلم مرد"},
        {"word": "die Lehrerin", "translation": "معلم زن"},
        {"word": "der Verkäufer", "translation": "فروشنده مرد"},
        {"word": "die Verkäuferin", "translation": "فروشنده زن"},
        {"word": "der Journalist", "translation": "روزنامه‌نگار مرد"},
        {"word": "die Journalistin", "translation": "روزنامه‌نگار زن"},
        {"word": "der Student", "translation": "دانشجو مرد"},
        {"word": "die Studentin", "translation": "دانشجوی زن"},
        {"word": "der Programmierer", "translation": "برنامه‌نویس مرد"},
        {"word": "die Programmiererin", "translation": "برنامه‌نویس زن"},
        {"word": "der Ingenieur", "translation": "مهندس مرد"},
        {"word": "die Ingenieurin", "translation": "مهندس زن"},
        {"word": "der Kellner", "translation": "گارسون مرد"},
        {"word": "die Kellnerin", "translation": "گارسون زن"},
        {"word": "der Taxifahrer", "translation": "راننده تاکسی"},
        {"word": "das Alter", "translation": "سن"},
        {"word": "das Jahr", "translation": "سال"},
        {"word": "arbeiten", "translation": "کار کردن"},
        {"word": "studieren", "translation": "تحصیل کردن (دانشگاه)"},
        {"word": "machten", "translation": "انجام دادن"},
        {"word": "ledig", "translation": "مجرد"},
        {"word": "verheiratet", "translation": "متأهل"},
        {"word": "geschieden", "translation": "طلاق‌گرفته"},
        {"word": "verwitwet", "translation": "بیوه"},
        {"word": "jung", "translation": "جوان"},
        {"word": "alt", "translation": "پیر / ساله"}
      ],
      "sentences": [
        {"de": "Was bist du von Beruf?", "fa": "شغلت چیست؟"},
        {"de": "Ich bin Student.", "fa": "من دانشجو هستم."},
        {"de": "Was machen Sie beruflich?", "fa": "شغل شما چیست؟"},
        {"de": "Ich arbeite als Programmierer.", "fa": "من به عنوان برنامه‌نویس کار می‌کنم."},
        {"de": "Sie ist Ärztin von Beruf.", "fa": "او شغلش پزشک است."},
        {"de": "Wie alt bist du?", "fa": "چند سالته؟"},
        {"de": "Ich bin 19 Jahre alt.", "fa": "من ۱۹ ساله هستم."},
        {"de": "Wo arbeitest du?", "fa": "کجا کار می‌کنی؟"},
        {"de": "Ich arbeite bei Siemens.", "fa": "من در شرکت زیمنس کار می‌کنم."},
        {"de": "Ich arbeite in einer Firma.", "fa": "من در یک شرکت کار می‌کنم."},
        {"de": "Ich studiere Informatik.", "fa": "من علوم کامپیوتر می‌خوانم."},
        {"de": "Bist du verheiratet?", "fa": "آیا متأهل هستی؟"},
        {"de": "Nein, ich bin ledig.", "fa": "نه، من مجرد هستم."},
        {"de": "Ich mache ein Praktikum.", "fa": "من دارم دوره کارآموزی می‌گذرانم."}
      ]
    },
    {
      "title": "Lektion 3",
      "name": "Das ist meine Mutter",
      "topic": "خانواده و اعضای خانواده",
      "grammar": "mein / meine + dein / deine + haben",
      "words": [
        {"word": "die Familie", "translation": "خانواده"},
        {"word": "die Mutter", "translation": "مادر"},
        {"word": "der Vater", "translation": "پدر"},
        {"word": "die Eltern", "translation": "والدین"},
        {"word": "der Bruder", "translation": "برادر"},
        {"word": "die Schwester", "translation": "خواهر"},
        {"word": "die Geschwister", "translation": "خواهر و برادرها"},
        {"word": "der Sohn", "translation": "پسر (فرزند)"},
        {"word": "die Tochter", "translation": "دختر (فرزند)"},
        {"word": "der Mann", "translation": "مرد / شوهر"},
        {"word": "die Frau", "translation": "زن / همسر"},
        {"word": "das Kind", "translation": "بچه"},
        {"word": "die Kinder", "translation": "بچه‌ها"},
        {"word": "die Oma", "translation": "مادربزرگ"},
        {"word": "der Opa", "translation": "پدربزرگ"},
        {"word": "die Großeltern", "translation": "پدربزرگ و مادربزرگ"},
        {"word": "der Onkel", "translation": "عمو / دایی"},
        {"word": "die Tante", "translation": "عمه / خاله"},
        {"word": "der Cousin", "translation": "پسرعمو/دایی/عمه/خاله"},
        {"word": "die Cousine", "translation": "دخترعمو/دایی/عمه/خاله"},
        {"word": "allein", "translation": "تنها"},
        {"word": "zusammen", "translation": "با هم"},
        {"word": "haben", "translation": "داشتن"}
      ],
      "sentences": [
        {"de": "Das ist meine Mutter.", "fa": "این مادر من است."},
        {"de": "Das ist mein Vater.", "fa": "این پدر من است."},
        {"de": "Das ist mein Bruder.", "fa": "این برادر من است."},
        {"de": "Das ist meine Schwester.", "fa": "این خواهر من است."},
        {"de": "Wie heißt deine Mutter?", "fa": "اسم مادرت چیست؟"},
        {"de": "Hast du Geschwister?", "fa": "خواهر و برادر داری؟"},
        {"de": "Ja, ich habe einen Bruder und eine Schwester.", "fa": "بله، یک برادر و یک خواهر دارم."},
        {"de": "Nein, ich habe keine Geschwister.", "fa": "نه، خواهر و برادر ندارم."},
        {"de": "Haben Sie Kinder?", "fa": "شما فرزندی دارید؟"},
        {"de": "Ja, wir haben zwei Kinder.", "fa": "بله، ما دو فرزند داریم."},
        {"de": "Meine Familie ist groß.", "fa": "خانواده من بزرگ است."},
        {"de": "Meine Eltern wohnen im Iran.", "fa": "والدین من در ایران زندگی می‌کنند."}
      ]
    },
    {
      "title": "Lektion 4",
      "name": "Der Tisch ist schön!",
      "topic": "وسایل خانه، خرید و توصیف اشیا",
      "grammar": "der / die / das + sein + صفت + پرسیدن قیمت",
      "words": [
        {"word": "der Tisch", "translation": "میز"},
        {"word": "der Stuhl", "translation": "صندلی"},
        {"word": "das Bett", "translation": "تخت"},
        {"word": "die Lampe", "translation": "چراغ"},
        {"word": "der Schrank", "translation": "کمد"},
        {"word": "das Sofa", "translation": "مبل"},
        {"word": "der Sessel", "translation": "مبل راحتی تک‌نفره"},
        {"word": "das Regal", "translation": "قفسه / کتابخانه"},
        {"word": "der Teppich", "translation": "فرش"},
        {"word": "das Bild", "translation": "عکس / تابلو"},
        {"word": "die Tür", "translation": "در"},
        {"word": "das Fenster", "translation": "پنجره"},
        {"word": "die Küche", "translation": "آشپزخانه"},
        {"word": "das Zimmer", "translation": "اتاق"},
        {"word": "der Euro", "translation": "یورو"},
        {"word": "der Cent", "translation": "سنت"},
        {"word": "schön", "translation": "زیبا"},
        {"word": "hässlich", "translation": "زشت"},
        {"word": "groß", "translation": "بزرگ"},
        {"word": "klein", "translation": "کوچک"},
        {"word": "neu", "translation": "جدید"},
        {"word": "alt", "translation": "قدیمی / کهنه"},
        {"word": "teuer", "translation": "گران"},
        {"word": "billig", "translation": "ارزان"},
        {"word": "praktisch", "translation": "کاربردی"},
        {"word": "bequem", "translation": "راحت"},
        {"word": "kosten", "translation": "قیمت داشتن"}
      ],
      "sentences": [
        {"de": "Der Tisch ist schön.", "fa": "میز زیبا است."},
        {"de": "Die Lampe ist neu.", "fa": "چراغ جدید است."},
        {"de": "Das Sofa ist bequem.", "fa": "مبل راحت است."},
        {"de": "Der Schrank ist sehr groß.", "fa": "کمد خیلی بزرگ است."},
        {"de": "Das Zimmer ist klein, aber schön.", "fa": "اتاق کوچک است اما زیباست."},
        {"de": "Wie viel kostet das Bett?", "fa": "قیمت این تخت چقدر است؟"},
        {"de": "Das kostet 200 Euro.", "fa": "این ۲۰۰ یورو قیمت دارد."},
        {"de": "Ist der Teppich teuer?", "fa": "آیا فرش گران است؟"},
        {"de": "Nein, er ist sehr billig.", "fa": "نه، آن بسیار ارزان است."},
        {"de": "Wie finden Sie den Sessel?", "fa": "نظر شما در مورد این صندلی راحتی چیست؟"}
      ]
    },
    {
      "title": "Lektion 5",
      "name": "Was ist das?",
      "topic": "اشیای روزمره و پرسیدن نام وسایل",
      "grammar": "ein / eine + kein / keine + Akkusativ مقدماتی",
      "words": [
        {"word": "der Bleistift", "translation": "مداد"},
        {"word": "der Kugelschreiber", "translation": "خودکار"},
        {"word": "das Buch", "translation": "کتاب"},
        {"word": "das Heft", "translation": "دفترچه"},
        {"word": "die Flasche", "translation": "بطری"},
        {"word": "die Brille", "translation": "عینک"},
        {"word": "die Tasche", "translation": "کیف"},
        {"word": "der Schlüssel", "translation": "کلید"},
        {"word": "das Handy", "translation": "موبایل"},
        {"word": "der Computer", "translation": "کامپیوتر"},
        {"word": "das Feuerzeug", "translation": "فندک"},
        {"word": "die Geldbörse", "translation": "کیف پول"},
        {"word": "die Uhr", "translation": "ساعت"},
        {"word": "das Foto", "translation": "عکس"},
        {"word": "der Rucksack", "translation": "کوله‌پشتی"},
        {"word": "der Regenschirm", "translation": "چتر"},
        {"word": "die Zeitung", "translation": "روزنامه"},
        {"word": "brauchen", "translation": "نیاز داشتن"},
        {"word": "suchen", "translation": "گشتن / دنبال چیزی بودن"}
      ],
      "sentences": [
        {"de": "Was ist das?", "fa": "این چیست؟"},
        {"de": "Das ist eine Tasche.", "fa": "این یک کیف است."},
        {"de": "Das ist ein Buch.", "fa": "این یک کتاب است."},
        {"de": "Ist das ein Regenschirm?", "fa": "آیا این یک چتر است؟"},
        {"de": "Nein, das ist kein Regenschirm.", "fa": "نه، این چتر نیست."},
        {"de": "Wie heißt das auf Deutsch?", "fa": "این به آلمانی چه می‌شود؟"},
        {"de": "Wie schreibt man das?", "fa": "چطور نوشته می‌شود؟"},
        {"de": "Wie spricht man das aus?", "fa": "چطور تلفظ می‌شود؟"},
        {"de": "Das weiß ich nicht.", "fa": "این را نمی‌دانم."},
        {"de": "Ich brauche einen Schlüssel.", "fa": "من به یک کلید نیاز دارم."},
        {"de": "Ich habe keine Brille.", "fa": "من عینک ندارم."},
        {"de": "Ich suche mein Handy.", "fa": "من دنبال موبایلم می‌گردم."}
      ]
    },
    {
      "title": "Lektion 6",
      "name": "Ich brauche kein Büro",
      "topic": "محل کار و تکنولوژی",
      "grammar": "Akkusativ مقدماتی + kein / keine / keinen + haben / brauchen",
      "words": [
        {"word": "das Büro", "translation": "دفتر کار"},
        {"word": "der Schreibtisch", "translation": "میز کار"},
        {"word": "der Computer", "translation": "کامپیوتر"},
        {"word": "der Laptop", "translation": "لپ‌تاپ"},
        {"word": "der Drucker", "translation": "پرینتر"},
        {"word": "der Bildschirm", "translation": "مانیتور / صفحه نمایش"},
        {"word": "die Tastatur", "translation": "کیبورد"},
        {"word": "die Maus", "translation": "موس"},
        {"word": "das Telefon", "translation": "تلفن"},
        {"word": "das Papier", "translation": "کاغذ"},
        {"word": "der Stift", "translation": "مداد / خودکار"},
        {"word": "die Rechnung", "translation": "فاکتور"},
        {"word": "der Kalender", "translation": "تقویم"},
        {"word": "das Formular", "translation": "فرم"},
        {"word": "der Chef", "translation": "رئیس مرد"},
        {"word": "die Chefin", "translation": "رئیس زن"},
        {"word": "schreiben", "translation": "نوشتن"},
        {"word": "lesen", "translation": "خواندن"},
        {"word": "anrufen", "translation": "تلفن زدن"}
      ],
      "sentences": [
        {"de": "Ich habe einen Laptop.", "fa": "من یک لپ‌تاپ دارم."},
        {"de": "Ich brauche kein Büro.", "fa": "من به دفتر نیاز ندارم."},
        {"de": "Hast du einen Computer?", "fa": "کامپیوتر داری؟"},
        {"de": "Ich habe keinen Drucker.", "fa": "من پرینتر ندارم."},
        {"de": "Wo ist der Schlüssel?", "fa": "کلید کجاست؟"},
        {"de": "Ich brauche einen neuen Stift.", "fa": "من به یک خودکار جدید نیاز دارم."},
        {"de": "Ich schreibe eine E-Mail.", "fa": "من دارم یک ایمیل می‌نویسم."},
        {"de": "Herr Müller liest die Rechnung.", "fa": "آقای مولر دارد فاکتور را می‌خواند."},
        {"de": "Der Chef ist nicht im Büro.", "fa": "رئیس در دفتر نیست."}
      ]
    },
    {
      "title": "Lektion 7",
      "name": "Du kannst wirklich toll!",
      "topic": "اوقات فراغت، سرگرمی و توانایی",
      "grammar": "können + مصدر در انتهای جمله",
      "words": [
        {"word": "das Hobby", "translation": "سرگرمی"},
        {"word": "der Sport", "translation": "ورزش"},
        {"word": "spielen", "translation": "بازی کردن"},
        {"word": "Fußball", "translation": "فوتبال"},
        {"word": "Tennis", "translation": "تنیس"},
        {"word": "Gitarre", "translation": "گیتار"},
        {"word": "Klavier", "translation": "پیانو"},
        {"word": "schwimmen", "translation": "شنا کردن"},
        {"word": "tanzen", "translation": "رقصیدن"},
        {"word": "singen", "translation": "آواز خواندن"},
        {"word": "kochen", "translation": "آشپزی کردن"},
        {"word": "backen", "translation": "پختن (شیرینی/نان)"},
        {"word": "malen", "translation": "نقاشی کشیدن"},
        {"word": "fotografieren", "translation": "عکاسی کردن"},
        {"word": "Musik hören", "translation": "موسیقی گوش دادن"},
        {"word": "Rad fahren", "translation": "دوچرخه‌سواری کردن"},
        {"word": "Ski fahren", "translation": "اسکی کردن"},
        {"word": "reisen", "translation": "سفر کردن"},
        {"word": "können", "translation": "توانستن"},
        {"word": "gut", "translation": "خوب"},
        {"word": "sehr gut", "translation": "خیلی خوب"},
        {"word": "super / toll", "translation": "فوق‌العاده / عالی"}
      ],
      "sentences": [
        {"de": "Ich kann schwimmen.", "fa": "من می‌توانم شنا کنم."},
        {"de": "Kannst du kochen?", "fa": "می‌توانی آشپزی کنی؟"},
        {"de": "Ja, ich kann gut kochen.", "fa": "بله، خوب می‌توانم آشپزی کنم."},
        {"de": "Ich kann nicht tanzen.", "fa": "من نمی‌توانم برقصم."},
        {"de": "Kannst du Gitarre spielen?", "fa": "می‌توانی گیتار بزنی؟"},
        {"de": "Er kann sehr gut Fußball spielen.", "fa": "او می‌تواند خیلی خوب فوتبال بازی کند."},
        {"de": "Ich spiele gern Computerspiele.", "fa": "من دوست دارم بازی کامپیوتری انجام دهم."},
        {"de": "Was machst du in der Freizeit?", "fa": "در وقت آزاد چه کار می‌کنی؟"},
        {"de": "Mein Hobby ist Fotografieren.", "fa": "سرگرمی من عکاسی است."}
      ]
    },
    {
      "title": "Lektion 8",
      "name": "Kein Problem. Ich habe Zeit!",
      "topic": "وقت آزاد، روزهای هفته، قرار و برنامه‌ریزی",
      "grammar": "روزهای هفته + am + ساعت با um + haben / treffen",
      "words": [
        {"word": "die Zeit", "translation": "زمان / وقت"},
        {"word": "der Termin", "translation": "قرار / وقت قبلی"},
        {"word": "heute", "translation": "امروز"},
        {"word": "morgen", "translation": "فردا"},
        {"word": "gestern", "translation": "دیروز"},
        {"word": "jetzt", "translation": "الان"},
        {"word": "später", "translation": "بعداً"},
        {"word": "Montag", "translation": "دوشنبه"},
        {"word": "Dienstag", "translation": "سه‌شنبه"},
        {"word": "Mittwoch", "translation": "چهارشنبه"},
        {"word": "Donnerstag", "translation": "پنجشنبه"},
        {"word": "Freitag", "translation": "جمعه"},
        {"word": "Samstag", "translation": "شنبه"},
        {"word": "Sonntag", "translation": "یکشنبه"},
        {"word": "das Wochenende", "translation": "آخر هفته"},
        {"word": "die Uhrzeit", "translation": "ساعت / زمان"},
        {"word": "frei", "translation": "آزاد"},
        {"word": "beschäftigt", "translation": "مشغول"},
        {"word": "pünktlich", "translation": "آن‌آن / به‌موقع"},
        {"word": "spät", "translation": "دیر"},
        {"word": "treffen", "translation": "ملاقات کردن"}
      ],
      "sentences": [
        {"de": "Hast du heute Zeit?", "fa": "امروز وقت داری؟"},
        {"de": "Ja, ich habe Zeit.", "fa": "بله، وقت دارم."},
        {"de": "Leider habe ich keine Zeit.", "fa": "متأسفانه وقت ندارم."},
        {"de": "Wie viel Uhr ist es?", "fa": "ساعت چند است؟"},
        {"de": "Es ist acht Uhr.", "fa": "ساعت هشت است."},
        {"de": "Wann treffen wir uns?", "fa": "کی همدیگر را ببینیم؟"},
        {"de": "Am Samstag um drei Uhr.", "fa": "شنبه ساعت سه."},
        {"de": "Ich habe am Montag einen Termin.", "fa": "من دوشنبه یک قرار دارم."},
        {"de": "Passt es dir am Freitag?", "fa": "جمعه برایت مناسب است؟"},
        {"de": "Bis später!", "fa": "بعداً می‌بینمت!"}
      ]
    },
    {
      "title": "Lektion 9",
      "name": "Ich möchte was essen, Onkel Harry",
      "topic": "غذا، نوشیدنی و سفارش دادن",
      "grammar": "möchten + Akkusativ مقدماتی + essen / trinken",
      "words": [
        {"word": "das Essen", "translation": "غذا"},
        {"word": "das Getränk", "translation": "نوشیدنی"},
        {"word": "das Brot", "translation": "نان"},
        {"word": "das Brötchen", "translation": "نان گرد کوچک"},
        {"word": "der Käse", "translation": "پنیر"},
        {"word": "die Butter", "translation": "کره"},
        {"word": "die Wurst", "translation": "سوسیس / کالباس"},
        {"word": "das Fleisch", "translation": "گوشت"},
        {"word": "der Fisch", "translation": "ماهی"},
        {"word": "der Reis", "translation": "برنج"},
        {"word": "die Kartoffel", "translation": "سیب‌زمینی"},
        {"word": "der Salat", "translation": "سالاد"},
        {"word": "die Suppe", "translation": "سوپ"},
        {"word": "der Apfel", "translation": "سیب"},
        {"word": "die Banane", "translation": "موز"},
        {"word": "das Wasser", "translation": "آب"},
        {"word": "der Kaffee", "translation": "قهوه"},
        {"word": "der Tee", "translation": "چای"},
        {"word": "die Milch", "translation": "شیر"},
        {"word": "der Saft", "translation": "آبمیوه"},
        {"word": "das Bier", "translation": "آبجو"},
        {"word": "der Wein", "translation": "شراب"},
        {"word": "essen", "translation": "خوردن"},
        {"word": "trinken", "translation": "نوشیدن"},
        {"word": "möchten", "translation": "خواستن / مایل بودن"},
        {"word": "lecker", "translation": "خوشمزه"}
      ],
      "sentences": [
        {"de": "Ich möchte etwas essen.", "fa": "می‌خواهم چیزی بخورم."},
        {"de": "Was möchtest du trinken?", "fa": "چه می‌خواهی بنوشی؟"},
        {"de": "Ich möchte einen Tee, bitte.", "fa": "لطفاً یک چای می‌خواهم."},
        {"de": "Möchtest du Kaffee?", "fa": "قهوه می‌خواهی؟"},
        {"de": "Ja, gern.", "fa": "بله، با کمال میل."},
        {"de": "Nein, danke.", "fa": "نه، ممنون."},
        {"de": "Ich esse gern Pizza.", "fa": "من دوست دارم پیتزا بخورم."},
        {"de": "Was möchten Sie bestellen?", "fa": "چه چیزی می‌خواهید سفارش دهید؟"},
        {"de": "Das Essen ist sehr lecker!", "fa": "غذا بسیار خوشمزه است!"}
      ]
    },
    {
      "title": "Lektion 10",
      "name": "Ich steige jetzt in die U-Bahn ein",
      "topic": "حمل‌ونقل، سفر و مسیر",
      "grammar": "افعال جداشدنی مثل einsteigen / aussteigen + fahren",
      "words": [
        {"word": "die U-Bahn", "translation": "مترو"},
        {"word": "der Bus", "translation": "اتوبوس"},
        {"word": "der Zug", "translation": "قطار"},
        {"word": "das Taxi", "translation": "تاکسی"},
        {"word": "das Auto", "translation": "ماشین"},
        {"word": "das Fahrrad", "translation": "دوچرخه"},
        {"word": "das Flugzeug", "translation": "هواپیما"},
        {"word": "der Bahnhof", "translation": "ایستگاه قطار"},
        {"word": "die Haltestelle", "translation": "ایستگاه اتوبوس/تراموا"},
        {"word": "der Flughafen", "translation": "فرودگاه"},
        {"word": "die Fahrkarte", "translation": "بلیت"},
        {"word": "das Gleis", "translation": "سکوی قطار"},
        {"word": "die Verspätung", "translation": "تأخیر"},
        {"word": "fahren", "translation": "رفتن با وسیله نقلیه"},
        {"word": "fliegen", "translation": "پرواز کردن"},
        {"word": "einsteigen", "translation": "سوار شدن"},
        {"word": "aussteigen", "translation": "پیاده شدن"},
        {"word": "umsteigen", "translation": "خط عوض کردن (قطار/اتوبوس)"},
        {"word": "ankommen", "translation": "رسیدن"},
        {"word": "abfahren", "translation": "حرکت کردن (وسیله نقلیه)"}
      ],
      "sentences": [
        {"de": "Ich fahre mit dem Bus.", "fa": "با اتوبوس می‌روم."},
        {"de": "Ich steige in die U-Bahn ein.", "fa": "سوار مترو می‌شوم."},
        {"de": "Ich steige hier aus.", "fa": "اینجا پیاده می‌شوم."},
        {"de": "Wo ist der Bahnhof?", "fa": "ایستگاه قطار کجاست؟"},
        {"de": "Der Zug fährt um 9 Uhr ab.", "fa": "قطار ساعت ۹ حرکت می‌کند."},
        {"de": "Wann kommt der Zug an?", "fa": "قطار کی می‌رسد؟"},
        {"de": "Du musst in Frankfurt umsteigen.", "fa": "تو باید در فرانکفورت خط عوض کنی."},
        {"de": "Der Bus hat 10 Minuten Verspätung.", "fa": "اتوبوس ۱۰ دقیقه تأخیر دارد."},
        {"de": "Ich nehme ein Taxi.", "fa": "من یک تاکسی می‌گیرم."}
      ]
    },
    {
      "title": "Lektion 11",
      "name": "Was hast du heute gemacht?",
      "topic": "کارهای روزمره و صحبت درباره گذشته",
      "grammar": "Perfekt با haben / sein + Partizip II",
      "words": [
        {"word": "aufstehen", "translation": "بیدار شدن / از تخت بلند شدن"},
        {"word": "frühstücken", "translation": "صبحانه خوردن"},
        {"word": "einkaufen", "translation": "خرید کردن"},
        {"word": "aufräumen", "translation": "مرتب کردن / تمیز کردن"},
        {"word": "kochen", "translation": "آشپزی کردن"},
        {"word": "schlafen", "translation": "خوابیدن"},
        {"word": "fernsehen", "translation": "تلویزیون دیدن"},
        {"word": "spazieren gehen", "translation": "پیاده‌روی کردن"},
        {"word": "arbeiten", "translation": "کار کردن"},
        {"word": "lernen", "translation": "درس خواندن"},
        {"word": "der Supermarkt", "translation": "سوپرمارکت"},
        {"word": "das Frühstück", "translation": "صبحانه"},
        {"word": "am Morgen", "translation": "صبح"},
        {"word": "am Mittag", "translation": "ظهر"},
        {"word": "am Abend", "translation": "عصر / شب"},
        {"word": "gestern", "translation": "دیروز"}
      ],
      "sentences": [
        {"de": "Was hast du heute gemacht?", "fa": "امروز چه کار کردی؟"},
        {"de": "Ich bin um 7 Uhr aufgestanden.", "fa": "من ساعت ۷ بیدار شدم."},
        {"de": "Ich habe gearbeitet.", "fa": "کار کردم."},
        {"de": "Ich habe Deutsch gelernt.", "fa": "آلمانی خواندم."},
        {"de": "Ich habe im Supermarkt eingekauft.", "fa": "در سوپرمارکت خرید کردم."},
        {"de": "Wir haben zusammen gekocht.", "fa": "ما با هم آشپزی کردیم."},
        {"de": "Ich habe ferngesehen.", "fa": "تلویزیون تماشا کردم."},
        {"de": "Ich bin spazieren gegangen.", "fa": "به پیاده‌روی رفتم."},
        {"de": "Er hat seine Mutter angerufen.", "fa": "او به مادرش زنگ زد."}
      ]
    },
    {
      "title": "Lektion 12",
      "name": "Was ist denn hier passiert?",
      "topic": "اتفاقات گذشته، مشکلات و توضیح اتفاق",
      "grammar": "مرور Perfekt + تفاوت haben / sein + Partizip II",
      "words": [
        {"word": "passieren", "translation": "اتفاق افتادن"},
        {"word": "verlieren", "translation": "گم کردن / باختن"},
        {"word": "vergessen", "translation": "فراموش کردن"},
        {"word": "suchen", "translation": "جست‌وجو کردن"},
        {"word": "finden", "translation": "پیدا کردن"},
        {"word": "reparieren", "translation": "تعمیر کردن"},
        {"word": "bleiben", "translation": "ماندن"},
        {"word": "helfen", "translation": "کمک کردن"},
        {"word": "kaputt", "translation": "خراب"},
        {"word": "weg", "translation": "رفته / گم‌شده"},
        {"word": "der Unfall", "translation": "تصادف / حادثه"},
        {"word": "das Problem", "translation": "مشکل"},
        {"word": "die Hilfe", "translation": "کمک"},
        {"word": "plötzlich", "translation": "ناگهان"},
        {"word": "leider", "translation": "متأسفانه"},
        {"word": "zum Glück", "translation": "خوشبختانه"}
      ],
      "sentences": [
        {"de": "Was ist passiert?", "fa": "چی شده؟"},
        {"de": "Was ist denn hier passiert?", "fa": "اینجا چه اتفاقی افتاده؟"},
        {"de": "Mein Handy ist kaputtgegangen.", "fa": "موبایلم خراب شد."},
        {"de": "Ich habe meinen Schlüssel verloren.", "fa": "کلیدم را گم کرده‌ام."},
        {"de": "Ich habe das vergessen.", "fa": "آن را فراموش کردم."},
        {"de": "Hast du deine Tasche gefunden?", "fa": "کیفت را پیدا کردی؟"},
        {"de": "Kannst du mir helfen?", "fa": "می‌توانی به من کمک کنی؟"},
        {"de": "Er ist gestern zu Hause geblieben.", "fa": "او دیروز در خانه ماند."},
        {"de": "Kein Problem, alles ist gut.", "fa": "مشکلی نیست، همه چیز خوب است."}
      ]
    }
  ];
}